/**
 * Dictionary Loader — loads translation JSON and provides typed access
 * Auto-generated by scripts/generate_i18n.py — DO NOT EDIT MANUALLY
 */
import type { Locale } from "./i18n"

const dictionaryLoaders: Record<Locale, () => Promise<Record<string, unknown>>> = {
  en: () => import("@/dictionaries/en.json").then((m) => m.default),
  id: () => import("@/dictionaries/id.json").then((m) => m.default),
  vi: () => import("@/dictionaries/vi.json").then((m) => m.default),
  th: () => import("@/dictionaries/th.json").then((m) => m.default),
  es: () => import("@/dictionaries/es.json").then((m) => m.default),
  "pt-br": () => import("@/dictionaries/pt-br.json").then((m) => m.default),
  zh: () => import("@/dictionaries/zh.json").then((m) => m.default),
  ja: () => import("@/dictionaries/ja.json").then((m) => m.default),
  ko: () => import("@/dictionaries/ko.json").then((m) => m.default),
  ar: () => import("@/dictionaries/ar.json").then((m) => m.default),
  hi: () => import("@/dictionaries/hi.json").then((m) => m.default),
  fr: () => import("@/dictionaries/fr.json").then((m) => m.default),
  de: () => import("@/dictionaries/de.json").then((m) => m.default),
  ru: () => import("@/dictionaries/ru.json").then((m) => m.default),
  tr: () => import("@/dictionaries/tr.json").then((m) => m.default),
  it: () => import("@/dictionaries/it.json").then((m) => m.default),
  pl: () => import("@/dictionaries/pl.json").then((m) => m.default),
  nl: () => import("@/dictionaries/nl.json").then((m) => m.default),
  ms: () => import("@/dictionaries/ms.json").then((m) => m.default),
  fil: () => import("@/dictionaries/fil.json").then((m) => m.default),
}

/** Type representing the nested dictionary structure */
export type Dictionary = {
  meta: {
    title: string
    description: string
    keywords: string
  }
  hero: {
    badge: string
    title: string
    titleHighlight: string
    subtitle: string
    placeholder: string
    cta: string
    trust: string
  }
  download: {
    title: string
    mp4: string
    mp3: string
    hd: string
    copyLink: string
    pasteAgain: string
    loading: string
    error: string
    noVideo: string
  }
  features: {
    title: string
    subtitle: string
    items: Array<{ title: string; desc: string }>
  }
  stats: {
    videos: string
    users: string
    countries: string
  }
  howTo: {
    title: string
    subtitle: string
    steps: Array<{ title: string; desc: string }>
  }
  faq: {
    title: string
    subtitle: string
    questions: Array<{ q: string; a: string }>
  }
  footer: {
    copyright: string
    links: {
      faq: string
      privacy: string
      terms: string
      feedback: string
      help: string
    }
  }
  ui: {
    privacyFirst: string
    noRegistration: string
    allDevices: string
    discover: string
    processing: string
    processingVideo: string
    photoMode: string
    photos: string
    downloadVerb: string
    downloadAnother: string
    builtDifferent: string
    builtDifferentSub: string
    threeSteps: string
    thatsIt: string
    noComplexity: string
    everyScreen: string
    sameExperience: string
    iphoneAndroid: string
    downloadMobile: string
    windowsMacLinux: string
    downloadDesktop: string
    freeForever: string
    downloadsToday: string
    languages: string
    youAsk: string
    weAnswer: string
    readyToDownload: string
    ctaSubtitle: string
    startDownloading: string
    footerPitch: string
    legal: string
    support: string
    terms: string
    privacy: string
    disclaimer: string
    forPersonalUse: string
    stepMobile1: string
    stepMobile2: string
    stepMobile3: string
    stepMobile4: string
    stepMobile5: string
    stepDesktop1: string
    stepDesktop2: string
    stepDesktop3: string
    stepDesktop4: string
    stepDesktop5: string
  }
  language: string
}

const cache = new Map<Locale, Dictionary>()

export async function getDictionary(locale: Locale): Promise<Dictionary> {
  const cached = cache.get(locale)
  if (cached) return cached

  const loader = dictionaryLoaders[locale]
  if (!loader) {
    const fallback = await dictionaryLoaders.en()
    cache.set(locale, fallback as Dictionary)
    return fallback as Dictionary
  }

  const dict = (await loader()) as Dictionary
  cache.set(locale, dict)
  return dict
}

export function getCachedDict(locale: Locale): Dictionary | undefined {
  return cache.get(locale)
}
