/**
 * i18n Configuration — 20-language dictionary-based localization
 *
 * URL strategy: / → EN (default), /id → Indonesian, /zh → Chinese, etc.
 * Auto-generated by scripts/generate_i18n.py — DO NOT EDIT MANUALLY
 */

export const locales = ["en", "id", "vi", "th", "es", "pt-br", "zh", "ja", "ko", "ar", "hi", "fr", "de", "ru", "tr", "it", "pl", "nl", "ms", "fil"] as const
export type Locale = (typeof locales)[number]

export const defaultLocale: Locale = "en"

/** Locale display names (used in language switcher) */
export const localeLabels: Record<Locale, string> = {
  en: "English",
  id: "Bahasa Indonesia",
  vi: "Tiếng Việt",
  th: "ไทย",
  es: "Español",
  "pt-br": "Português",
  zh: "简体中文",
  ja: "日本語",
  ko: "한국어",
  ar: "العربية",
  hi: "हिन्दी",
  fr: "Français",
  de: "Deutsch",
  ru: "Русский",
  tr: "Türkçe",
  it: "Italiano",
  pl: "Polski",
  nl: "Nederlands",
  ms: "Bahasa Melayu",
  fil: "Filipino",
}

/** Locale native names for the switcher */
export const localeNative: Record<Locale, string> = {
  en: "English",
  id: "Bahasa Indonesia",
  vi: "Tiếng Việt",
  th: "ไทย",
  es: "Español",
  "pt-br": "Português",
  zh: "简体中文",
  ja: "日本語",
  ko: "한국어",
  ar: "العربية",
  hi: "हिन्दी",
  fr: "Français",
  de: "Deutsch",
  ru: "Русский",
  tr: "Türkçe",
  it: "Italiano",
  pl: "Polski",
  nl: "Nederlands",
  ms: "Bahasa Melayu",
  fil: "Filipino",
}

/** HTML lang attribute values */
export const localeHtmlLang: Record<Locale, string> = {
  en: "en",
  id: "id",
  vi: "vi",
  th: "th",
  es: "es-419",
  "pt-br": "pt-BR",
  zh: "zh-Hans",
  ja: "ja",
  ko: "ko",
  ar: "ar",
  hi: "hi",
  fr: "fr",
  de: "de",
  ru: "ru",
  tr: "tr",
  it: "it",
  pl: "pl",
  nl: "nl",
  ms: "ms",
  fil: "fil",
}

/** OpenGraph locale values */
export const localeOgLocale: Record<Locale, string> = {
  en: "en_US",
  id: "id_ID",
  vi: "vi_VN",
  th: "th_TH",
  es: "es_419",
  "pt-br": "pt_BR",
  zh: "zh_CN",
  ja: "ja_JP",
  ko: "ko_KR",
  ar: "ar_SA",
  hi: "hi_IN",
  fr: "fr_FR",
  de: "de_DE",
  ru: "ru_RU",
  tr: "tr_TR",
  it: "it_IT",
  pl: "pl_PL",
  nl: "nl_NL",
  ms: "ms_MY",
  fil: "fil_PH",
}

/**
 * Detect locale from Accept-Language header
 */
export function detectLocale(acceptLanguage: string | null): Locale {
  if (!acceptLanguage) return defaultLocale

  const lang = acceptLanguage.toLowerCase()

  // Indonesian (Bahasa Indonesia)
  if (lang.includes("id")) return "id"

  // Vietnamese (Tiếng Việt)
  if (lang.includes("vi")) return "vi"

  // Thai (ไทย)
  if (lang.includes("th")) return "th"

  // Spanish (Español)
  if (lang.includes("es-419") || lang.includes("es-mx") || lang.includes("es-ar") || lang.includes("es-cl") || lang.includes("es-co") || lang.includes("es-pe") || lang.includes("es")) return "es"

  // Portuguese (BR) (Português)
  if (lang.includes("pt-br") || lang.includes("pt_br") || lang.includes("pt")) return "pt-br"

  // Chinese (Simp) (简体中文)
  if (lang.includes("zh-cn") || lang.includes("zh-hans") || lang.includes("zh")) return "zh"

  // Japanese (日本語)
  if (lang.includes("ja")) return "ja"

  // Korean (한국어)
  if (lang.includes("ko")) return "ko"

  // Arabic (العربية)
  if (lang.includes("ar")) return "ar"

  // Hindi (हिन्दी)
  if (lang.includes("hi")) return "hi"

  // French (Français)
  if (lang.includes("fr")) return "fr"

  // German (Deutsch)
  if (lang.includes("de")) return "de"

  // Russian (Русский)
  if (lang.includes("ru")) return "ru"

  // Turkish (Türkçe)
  if (lang.includes("tr")) return "tr"

  // Italian (Italiano)
  if (lang.includes("it")) return "it"

  // Polish (Polski)
  if (lang.includes("pl")) return "pl"

  // Dutch (Nederlands)
  if (lang.includes("nl")) return "nl"

  // Malay (Bahasa Melayu)
  if (lang.includes("ms")) return "ms"

  // Filipino (Filipino)
  if (lang.includes("fil") || lang.includes("tl")) return "fil"

  return defaultLocale
}

/**
 * Get locale from URL pathname
 */
export function getLocaleFromPath(pathname: string): {
  locale: Locale
  cleanPath: string
} {
  const segments = pathname.split("/").filter(Boolean)
  const firstSegment = segments[0]

  if (firstSegment && locales.includes(firstSegment as Locale)) {
    return {
      locale: firstSegment as Locale,
      cleanPath: "/" + segments.slice(1).join("/") || "/",
    }
  }

  return { locale: defaultLocale, cleanPath: pathname }
}

/**
 * Build URL with locale prefix
 */
export function localizedPath(path: string, locale: Locale): string {
  const clean = path === "/" ? "" : path.replace(/\/$/, "")
  if (locale === defaultLocale) return clean || "/"
  return `/${locale}${clean}`
}
