#!/usr/bin/env python3
"""Generate content/blog/index.ts — static blog post index for Vercel deployment.
Reads all JSON files from content/blog/{locale}/ and generates a TypeScript index.
Run: python3 scripts/gen_blog_index.py
"""

import json
import os
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
BLOG_DIR = PROJECT / "content" / "blog"
OUTPUT = PROJECT / "content" / "blog" / "index.ts"

def main():
    imports = []
    posts = []

    for locale_dir in sorted(BLOG_DIR.iterdir()):
        if not locale_dir.is_dir():
            continue
        locale = locale_dir.name

        for file in sorted(locale_dir.glob("*.json")):
            # Generate a unique import name
            slug = file.stem
            import_name = f"{locale}_{slug}".replace("-", "_").replace(".", "_")
            rel_path = f"./{locale}/{file.name}"

            imports.append(f'import {import_name} from "{rel_path}"')
            posts.append(import_name)

    # Build the index file
    lines = [
        "// Auto-generated blog post index — DO NOT EDIT",
        "// Generated by scripts/gen_blog_index.py",
        "// Run after adding/removing blog posts.",
        "",
        'import type { BlogPost } from "@/lib/blog"',
        "",
    ] + imports + [
        "",
        f"export const blogPosts: BlogPost[] = [{', '.join(posts)}]",
        "",
    ]

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Generated {OUTPUT} with {len(posts)} posts")

if __name__ == "__main__":
    main()
