import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { allBlogPosts } from '@/content/blog/registry'
import { BreadcrumbSchema, FAQSchema } from '@/components/seo/schemas'

export function generateStaticParams() {
  return allBlogPosts.map((post) => ({ slug: post.slug }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const post = allBlogPosts.find((p) => p.slug === slug)
  if (!post) return { title: 'Not Found' }
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://ailomo.com'

  return {
    title: post.title,
    description: post.description,
    keywords: [post.targetKeyword, ...post.secondaryKeywords, post.category, 'ailomo'],
    openGraph: {
      title: post.title,
      description: post.description,
      type: 'article',
      url: `${siteUrl}/blog/${post.slug}`,
      tags: post.tags,
    },
    twitter: { card: 'summary_large_image', title: post.title, description: post.description },
    alternates: { canonical: `/blog/${post.slug}` },
    robots: { index: true, follow: true },
  }
}

export default async function BlogPost({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const post = allBlogPosts.find((p) => p.slug === slug)
  if (!post) notFound()

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://ailomo.com'
  const related = allBlogPosts
    .filter((p) => p.slug !== slug && p.category === post.category)
    .slice(0, 3)

  return (
    <div className="min-h-screen bg-background text-foreground">
      <BreadcrumbSchema
        items={[
          { name: 'Home', url: siteUrl },
          { name: 'Blog', url: `${siteUrl}/blog` },
          { name: post.title, url: `${siteUrl}/blog/${post.slug}` },
        ]}
      />
      <FAQSchema
        items={[
          { question: `What is the main topic of ${post.title}?`, answer: post.description },
          {
            question: `What tools or techniques are covered in this ${post.category.toLowerCase()} guide?`,
            answer: `This guide covers ${post.tags.slice(0, 5).join(', ')} and related techniques for content creators and marketers.`,
          },
        ]}
      />

      <article className="mx-auto max-w-3xl px-4 py-16 lg:py-24">
        {/* Breadcrumb */}
        <nav className="mb-8 text-sm text-muted-foreground">
          <Link href="/" className="hover:text-violet-400">Home</Link>
          <span className="mx-2">/</span>
          <Link href="/blog" className="hover:text-violet-400">Blog</Link>
          <span className="mx-2">/</span>
          <span className="text-violet-300">{post.category}</span>
        </nav>

        {/* Header */}
        <header className="mb-10">
          <div className="mb-4 flex items-center gap-3">
            <span className="rounded-full bg-violet-500/[0.08] px-3 py-1 text-xs font-medium text-violet-300">
              {post.category}
            </span>
            <span className="text-sm text-muted-foreground">{post.readingTime}</span>
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl lg:text-5xl leading-tight">
            {post.title}
          </h1>
          <p className="mt-4 text-lg text-muted-foreground leading-relaxed">
            {post.description}
          </p>
          <div className="mt-6 flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <span key={tag} className="rounded-md bg-white/[0.03] border border-white/[0.05] px-2.5 py-1 text-xs text-muted-foreground">
                #{tag}
              </span>
            ))}
          </div>
        </header>

        {/* Outline */}
        <div className="mb-10 rounded-2xl border border-violet-500/10 bg-violet-500/[0.02] p-6">
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-violet-300">In This Guide</h2>
          <ol className="space-y-2">
            {post.outline.map((item, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-muted-foreground">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-violet-500/[0.1] text-xs font-medium text-violet-300">
                  {i + 1}
                </span>
                {item}
              </li>
            ))}
          </ol>
        </div>

        {/* Content placeholder — filled by AI generation script */}
        <div className="prose prose-invert prose-violet max-w-none">
          <div className="rounded-2xl border border-white/[0.06] bg-white/[0.01] p-8 text-center">
            <p className="text-muted-foreground">
              This article is being generated by our AI pipeline.
              <br />
              <span className="text-sm">Run <code className="rounded bg-white/[0.05] px-2 py-0.5 text-xs">node scripts/seo/generate-blog.js</code> to populate content.</span>
            </p>
          </div>
        </div>

        {/* Keyword cluster — SEO internal linking */}
        <div className="mt-10 rounded-2xl border border-white/[0.06] bg-white/[0.01] p-6">
          <h3 className="mb-3 text-sm font-semibold text-violet-300">Related Keywords</h3>
          <div className="flex flex-wrap gap-2">
            {[post.targetKeyword, ...post.secondaryKeywords].map((kw) => (
              <span key={kw} className="rounded-md border border-white/[0.05] bg-white/[0.02] px-3 py-1 text-xs text-muted-foreground">
                {kw}
              </span>
            ))}
          </div>
        </div>
      </article>

      {/* Related posts */}
      {related.length > 0 && (
        <section className="mx-auto max-w-3xl px-4 pb-20">
          <h2 className="mb-6 text-xl font-bold">More in {post.category}</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {related.map((r) => (
              <Link
                key={r.slug}
                href={`/blog/${r.slug}`}
                className="rounded-xl border border-white/[0.06] bg-white/[0.01] p-5 hover:border-violet-500/15 transition-all"
              >
                <h3 className="font-medium text-sm leading-snug hover:text-violet-300 transition-colors">
                  {r.title}
                </h3>
                <p className="mt-2 text-xs text-muted-foreground line-clamp-2">{r.description}</p>
                <span className="mt-3 inline-block text-xs text-violet-400">{r.readingTime}</span>
              </Link>
            ))}
          </div>
        </section>
      )}
    </div>
  )
}
