import { Sparkles } from 'lucide-react'
import type { Dictionary } from '@/lib/dictionary'

export function Footer({ d }: { d: Dictionary }) {
  const links = {
    [d.footer.sections.product]: [{label:d.footer.links.features,href:'#features'},{label:d.footer.links.pricing,href:'#pricing'},{label:d.footer.links.faq,href:'#faq'}],
    [d.footer.sections.tools]: [{label:d.footer.links.yt2blog,href:'/tools/youtube-to-blog-post'},{label:d.footer.links.vid2twitter,href:'/tools/video-to-twitter-thread'},{label:d.footer.links.vid2xhs,href:'/tools/video-to-xiaohongshu'},{label:d.footer.links.podcast2article,href:'/tools/podcast-to-article'},{label:d.footer.links.allTools,href:'/tools'}],
    [d.footer.sections.legal]: [{label:d.footer.links.privacy,href:'/privacy'},{label:d.footer.links.terms,href:'/terms'}],
    [d.footer.sections.company]: [{label:d.footer.links.github,href:'https://github.com/aspendong-collab/repurposefast'},{label:d.footer.links.contact,href:'mailto:hi@ailomo.com'}],
  }
  return (<footer className="border-t border-white/[0.04] bg-background"><div className="mx-auto max-w-7xl px-6 py-16"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-1"><div className="flex items-center gap-2.5 mb-4"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500 to-purple-600"><Sparkles className="h-4 w-4 text-white"/></div><span className="font-bold text-lg"><span className="text-foreground">ailo</span><span className="text-violet-400">mo</span></span></div><p className="text-sm text-muted-foreground/50 leading-relaxed">{d.footer.tagline}</p></div>{Object.entries(links).map(([t,items])=>(<div key={t}><h4 className="font-semibold text-sm mb-4 text-foreground/80">{t}</h4><ul className="space-y-2.5">{items.map(({label,href})=><li key={label}><a href={href} target={href.startsWith('http')?'_blank':undefined} className="text-sm text-muted-foreground/50 hover:text-foreground/70 transition-colors">{label}</a></li>)}</ul></div>))}</div><div className="mt-14 pt-8 border-t border-white/[0.04] flex flex-col sm:flex-row items-center justify-between gap-3"><p className="text-xs text-muted-foreground/40">&copy; {new Date().getFullYear()} ailomo. {d.footer.copyright}</p><p className="text-xs text-muted-foreground/40">{d.footer.builtWith}</p></div></div></footer>)
}