import { FileText, Heart, MessageCircle, Linkedin, Mail, Search, Sparkles, GitFork, Subtitles } from 'lucide-react'
import type { Dictionary } from '@/lib/dictionary'

const ICONS = [FileText, FileText, Heart, MessageCircle, Linkedin, Search, Mail, Subtitles, Sparkles, GitFork]
const COLORS = ['text-orange-400 bg-orange-500/10','text-green-400 bg-green-500/10','text-red-400 bg-red-500/10','text-sky-400 bg-sky-500/10','text-blue-400 bg-blue-500/10','text-amber-400 bg-amber-500/10','text-cyan-400 bg-cyan-500/10','text-gray-400 bg-gray-500/10','text-purple-400 bg-purple-500/10','text-teal-400 bg-teal-500/10']
const LANGS = ['English','中文','日本語','한국어','Español','Français','Deutsch','Português','العربية','हिन्दी','Bahasa Indonesia','ไทย','Tiếng Việt','Русский','Italiano','Nederlands','Polski','Türkçe']

export function FormatShowcase({ d }: { d: Dictionary }) {
  return (<section className="py-24 sm:py-32 relative overflow-hidden"><div className="absolute inset-0 -z-10"><div className="absolute bottom-0 left-1/4 w-[500px] h-[500px] bg-cyan-500/5 rounded-full blur-[150px]"/></div><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="text-center mb-16"><p className="text-violet-400 text-sm font-semibold tracking-widest uppercase mb-4">{d.formats.outputLabel}</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight">{d.formats.outputTitle}<span className="g-text">{d.formats.outputHighlight}</span></h2><p className="text-muted-foreground mt-4 max-w-xl mx-auto">{d.formats.outputSubtitle}</p></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3 mb-20">{d.formats.formatNames.map((name,i)=>{const Icon=ICONS[i];return(<div key={name} className="group rounded-xl border border-border/50 bg-card/30 p-4 text-center hover:border-violet-500/20 hover:bg-card/50 transition-all"><div className={`inline-flex h-10 w-10 items-center justify-center rounded-lg ${COLORS[i]} mb-3`}><Icon className="h-5 w-5"/></div><h4 className="text-sm font-semibold">{name}</h4></div>)})}</div><div className="text-center mb-12"><p className="text-violet-400 text-sm font-semibold tracking-widest uppercase mb-4">{d.formats.langLabel}</p><h3 className="text-2xl sm:text-3xl font-bold">{d.formats.langTitle}</h3><p className="text-muted-foreground mt-2">{d.formats.langSubtitle}</p></div><div className="flex flex-wrap justify-center gap-2 max-w-3xl mx-auto">{LANGS.map(l=><span key={l} className="rounded-full border border-border/50 px-4 py-2 text-sm text-muted-foreground hover:border-violet-500/30 hover:text-foreground transition-colors cursor-default">{l}</span>)}<span className="rounded-full border border-violet-500/30 bg-violet-500/5 px-4 py-2 text-sm text-violet-400 font-medium">{d.formats.more}</span></div></div></section>)
}