import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { allBlogPosts } from '@/content/blog/registry'
import { BreadcrumbSchema, ArticleSchema, FAQSchema, SpeakableSchema } from '@/components/seo/schemas'
import { RelatedTools } from '@/components/seo/crosslinks'
import { getGitTimestamp } from '@/lib/seo-crosslink'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://ailomo.com'
const BLOG_LOCALES = ['en','zh','ja','ko','es','fr','de','pt','ar','hi','id','th','vi','ru','it']

export function generateStaticParams() {
  const params: { lang: string; slug: string }[] = []
  for (const lang of BLOG_LOCALES) {
    for (const post of allBlogPosts) {
      params.push({ lang, slug: post.slug })
    }
  }
  return params
}

export async function generateMetadata({ params }: { params: Promise<{ lang: string; slug: string }> }): Promise<Metadata> {
  const { lang, slug } = await params
  const post = allBlogPosts.find((p) => p.slug === slug)
  if (!post) return { title: 'Not Found' }

  const pubDate = getGitTimestamp('content/blog/registry.ts')
  return {
    title: post.title,
    description: post.description,
    keywords: [post.targetKeyword, ...post.secondaryKeywords, post.category, 'ailomo'],
    openGraph: {
      title: post.title, description: post.description, type: 'article',
      url: `${SITE_URL}/${lang}/blog/${slug}`, tags: post.tags,
      publishedTime: pubDate, modifiedTime: pubDate, authors: ['ailomo'],
    },
    alternates: { canonical: `${SITE_URL}/blog/${slug}` },
    robots: { index: true, follow: true },
  }
}

export default async function LangBlogPost({ params }: { params: Promise<{ lang: string; slug: string }> }) {
  const { lang, slug } = await params
  const post = allBlogPosts.find((p) => p.slug === slug)
  if (!post) notFound()

  const related = allBlogPosts.filter((p) => p.slug !== slug && p.category === post.category).slice(0, 3)
  const pubDate = getGitTimestamp('content/blog/registry.ts')

  return (
    <div className="min-h-screen bg-[#0a0a0b] text-white">
      <BreadcrumbSchema items={[
        { name: 'Home', url: `${SITE_URL}/${lang}` },
        { name: 'Blog', url: `${SITE_URL}/${lang}/blog` },
        { name: post.title, url: `${SITE_URL}/${lang}/blog/${slug}` },
      ]} />
      <ArticleSchema headline={post.title} description={post.description} datePublished={pubDate}
        dateModified={pubDate} url={`${SITE_URL}/${lang}/blog/${slug}`}
        keywords={[post.targetKeyword, ...post.secondaryKeywords]} />
      <FAQSchema questions={[
        { question: `What is ${post.title}?`, answer: post.description },
        { question: `What does this ${post.category.toLowerCase()} guide cover?`, answer: `This guide covers ${post.tags.slice(0, 5).join(', ')} and related techniques.` },
      ]} />
      <SpeakableSchema cssSelector="h1, .speakable" />

      <article className="mx-auto max-w-3xl px-4 py-16">
        <nav className="mb-8 text-sm text-muted-foreground">
          <Link href={`/${lang}`} className="hover:text-violet-300">Home</Link> / <Link href={`/${lang}/blog`} className="hover:text-violet-300">Blog</Link> / <span className="text-violet-300">{post.category}</span>
        </nav>

        <span className="inline-block rounded-full bg-violet-500/10 px-3 py-1 text-xs text-violet-300 mb-4">{post.category}</span>
        <h1 className="text-2xl font-bold tracking-tight sm:text-3xl lg:text-4xl">{post.title}</h1>

        <div className="mt-4 flex items-center gap-4 text-sm text-muted-foreground">
          <span>{post.readingTime} read</span>
          <span>·</span>
          <time dateTime={pubDate}>{new Date(pubDate).toLocaleDateString(lang, { year: 'numeric', month: 'long', day: 'numeric' })}</time>
        </div>

        <div className="mt-8 prose prose-invert max-w-none text-muted-foreground leading-relaxed">
          <p className="speakable">{post.description}</p>

          <h2 className="mt-8 text-xl font-bold text-white">Outline</h2>
          <ol className="space-y-1 ml-4">
            {post.outline.map((item, i) => (
              <li key={i} className="text-muted-foreground">{item}</li>
            ))}
          </ol>

          <div className="mt-8 rounded-2xl border border-violet-500/15 bg-violet-500/[0.04] p-6 text-center">
            <p className="text-sm text-violet-300">Full article is being generated by AI. Refresh soon to see the complete content.</p>
            <Link href="/" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-2.5 text-sm font-semibold text-black hover:bg-white/90">
              Try ailomo Free →
            </Link>
          </div>
        </div>

        <div className="mt-10 rounded-2xl border border-white/[0.06] bg-white/[0.01] p-6">
          <h3 className="mb-3 text-sm font-semibold text-violet-300">Related Keywords</h3>
          <div className="flex flex-wrap gap-2">
            {[post.targetKeyword, ...post.secondaryKeywords].map((kw) => (
              <span key={kw} className="rounded-md border border-white/[0.05] bg-white/[0.02] px-3 py-1 text-xs text-muted-foreground">{kw}</span>
            ))}
          </div>
        </div>
      </article>

      {related.length > 0 && (
        <section className="mx-auto max-w-3xl px-4 pb-12">
          <h2 className="mb-6 text-xl font-bold">More in {post.category}</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {related.map((r) => (
              <Link key={r.slug} href={`/${lang}/blog/${r.slug}`} className="rounded-xl border border-white/[0.06] bg-white/[0.01] p-5 hover:border-violet-500/15">
                <h3 className="font-medium text-sm">{r.title}</h3>
                <p className="mt-2 text-xs text-muted-foreground line-clamp-2">{r.description}</p>
              </Link>
            ))}
          </div>
        </section>
      )}

      <RelatedTools slug={slug} />
    </div>
  )
}
